### ISSUE TITLE
Server error 500 while trying to download the concept scheme's concepts as RDF/XML or Turtle 

### ISSUE THREAD

**Issue by OzgeOzkaya** [acdh-oeaw/vocabseditor#28]
Dear developers,

Thank you for such useful software. I have a concept scheme which has around 1120 concepts, while I try to download this concept scheme as RDF/XML or Turtle it gives me error. At the begining there wasn't such error, however I think with the increased number of concepts the system cannot download the concepts. Any suggestions in this point? Thank you!

![image](https://user-images.githubusercontent.com/28465079/152500563-bca5b858-b292-4c3e-a024-457aacb77b5f.png)

**Comment by csae8092** [comment]
I'm pretty sure this is a server time out issue. Solving this would be possible but this would need some time; I'll have to check back with our institute if and how we should proceed with this service.
* Are you using https://vocabseditor.acdh.oeaw.ac.at/ or do you have your own instance up and running because for the later I'd could provide some quick fix so you can dump your concept scheme via command-line
* If you are using our service and you need to export your scheme rather soon, you could write me an email peter.andorfer[at]oewa.ac.at with the ID of our concept scheme and I could it export for you

**Comment by OzgeOzkaya** [comment]
Dear Peter,

Many thanks for prompt response. We are using our own instance up and running so a command-line would really appreaciated on our side. Looking forward to hearing

**Comment by csae8092** [comment]
https://github.com/acdh-oeaw/vocabseditor/issues/29
